name: NOBRE FLORESTAL - GERAR APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Descompactar projeto
        run: |
          mkdir -p projeto
          unzip -q NOBRE_FLORESTAL_PROJETO_ATUALIZADO_GITHUB.zip -d projeto

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Localizar projeto Android
        id: localizar
        run: |
          GRADLEW=$(find projeto -type f -name gradlew | head -n 1)

          if [ -z "$GRADLEW" ]; then
            echo "ERRO: arquivo gradlew não encontrado dentro do ZIP"
            exit 1
          fi

          PASTA=$(dirname "$GRADLEW")

          echo "pasta=$PASTA" >> "$GITHUB_OUTPUT"

          chmod +x "$GRADLEW"

      - name: Gerar APK
        run: |
          cd "${{ steps.localizar.outputs.pasta }}"
          ./gradlew assembleDebug

      - name: Preparar APK
        run: |
          APK=$(find projeto -type f -name "*.apk" | head -n 1)

          if [ -z "$APK" ]; then
            echo "ERRO: APK não encontrado"
            exit 1
          fi

          cp "$APK" NOBRE-FLORESTAL-PROJETO.apk

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: NOBRE-FLORESTAL-PROJETO
          path: NOBRE-FLORESTAL-PROJETO.apk
