name: Gerar APK - NOBRE FLORESTAL PROJETO

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Extrair projeto
        run: unzip -o NOBRE_FLORESTAL_PROJETO_ATUALIZADO_GITHUB.zip -d projeto

      - name: Dar permissão ao Gradle
        run: chmod +x gradlew
        working-directory: projeto

      - name: Gerar APK
        run: ./gradlew assembleDebug
        working-directory: projeto

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: NOBRE-FLORESTAL-PROJETO-APK
          path: projeto/app/build/outputs/apk/debug/*.apk
